#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0


# shell-check all staged files, prevent commit if it finds errors
if command -v pacman > /dev/null && ! pacman -Qi shellcheck > /dev/null 2>&1; then
  sudo pacman -S --noconfirm --needed shellcheck
fi

if command -v shellcheck > /dev/null; then
  echo "$FILES" | xargs shellcheck
  exit $?
fi

exit 0
