name: dotfiles-ci

on:
  push:
    branches: [ "*" ]
    paths: [ "**.sh" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.sh" ]
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
