on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter Changed Files
        uses: dorny/paths-filter@v2.11.1
        id: changed-files
        with:
          filters: |
            shell:
              - '**/*.sh'
      - name: Run ShellCheck
        if: steps.changed-files.outputs.shell == 'true'
        uses: ludeeus/action-shellcheck@2.0.0
